---
name: Tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start redis
        run: |
          docker run --network host --detach redis:alpine
      - name: Ensure latest setuptools
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: |
          python -m pip install -e ".[test]"
      - name: Run nose
        run: |
          python -m nose
